// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuneVault.Infrastructure;

#nullable disable

namespace TuneVault.Infrastructure.Migrations
{
    [DbContext(typeof(TuneVaultDbContext))]
    [Migration("20260618041418_AddNewProfileFieldsToUser")]
    partial class AddNewProfileFieldsToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TuneVault.Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("TuneVault.Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "V-Pop Legends"
                        });
                });

            modelBuilder.Entity("TuneVault.Domain.Favorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("TuneVault.Domain.Follow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FollowerId", "TargetUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("TuneVault.Domain.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("OwnerId");

                    b.ToTable("MediaItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 59, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_1.mp3",
                            Genre = "Indie",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track1/300/300",
                            Title = "Sample Track 1",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 58, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_2.mp3",
                            Genre = "Pop",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track2/300/300",
                            Title = "Sample Track 2",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 57, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_3.mp3",
                            Genre = "Indie",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track3/300/300",
                            Title = "Sample Track 3",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 56, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_4.mp3",
                            Genre = "Pop",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track4/300/300",
                            Title = "Sample Track 4",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 55, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_5.mp3",
                            Genre = "Indie",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track5/300/300",
                            Title = "Sample Track 5",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 54, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_6.mp3",
                            Genre = "Pop",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track6/300/300",
                            Title = "Sample Track 6",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 53, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_7.mp3",
                            Genre = "Indie",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track7/300/300",
                            Title = "Sample Track 7",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 52, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_8.mp3",
                            Genre = "Pop",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track8/300/300",
                            Title = "Sample Track 8",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 51, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_9.mp3",
                            Genre = "Indie",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track9/300/300",
                            Title = "Sample Track 9",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            ArtistId = new Guid("6a37b7b4-757a-436a-b3d9-72fad1565a00"),
                            CreatedAt = new DateTime(2026, 6, 4, 23, 50, 0, 0, DateTimeKind.Utc),
                            DurationInSeconds = 180,
                            FilePath = "sample_10.mp3",
                            Genre = "Pop",
                            OwnerId = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            ThumbnailUrl = "https://picsum.photos/seed/track10/300/300",
                            Title = "Sample Track 10",
                            Type = 0
                        });
                });

            modelBuilder.Entity("TuneVault.Domain.MediaShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("MediaShares");
                });

            modelBuilder.Entity("TuneVault.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TuneVault.Domain.PlayHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayHistories");
                });

            modelBuilder.Entity("TuneVault.Domain.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("TuneVault.Domain.PlaylistTrack", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlaylistId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("TuneVault.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3872327a-4302-4e5c-a58a-ca48edd2b108"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Administrator",
                            Email = "admin@tunevault.com",
                            PasswordHash = "8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TuneVault.Domain.Album", b =>
                {
                    b.HasOne("TuneVault.Domain.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("TuneVault.Domain.Favorite", b =>
                {
                    b.HasOne("TuneVault.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuneVault.Domain.Follow", b =>
                {
                    b.HasOne("TuneVault.Domain.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("TuneVault.Domain.MediaItem", b =>
                {
                    b.HasOne("TuneVault.Domain.Album", "Album")
                        .WithMany("MediaItems")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuneVault.Domain.Artist", "Artist")
                        .WithMany("MediaItems")
                        .HasForeignKey("ArtistId");

                    b.HasOne("TuneVault.Domain.User", "Owner")
                        .WithMany("UploadedItems")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TuneVault.Domain.MediaShare", b =>
                {
                    b.HasOne("TuneVault.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId");

                    b.HasOne("TuneVault.Domain.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TuneVault.Domain.PlayHistory", b =>
                {
                    b.HasOne("TuneVault.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuneVault.Domain.Playlist", b =>
                {
                    b.HasOne("TuneVault.Domain.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuneVault.Domain.PlaylistTrack", b =>
                {
                    b.HasOne("TuneVault.Domain.MediaItem", "MediaItem")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("TuneVault.Domain.Album", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("TuneVault.Domain.Artist", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("TuneVault.Domain.MediaItem", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("TuneVault.Domain.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("TuneVault.Domain.User", b =>
                {
                    b.Navigation("Playlists");

                    b.Navigation("UploadedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
